CREATE TABLE "GROUPS_TEST"
(
  "GROUP_NUMBER" NUMBER(4, 0) UNIQUE NOT NULL,
  "FACULTY"      VARCHAR2(100) DEFAULT '-',
  "ID"           NUMBER(10, 0),
  CHECK (GROUP_NUMBER > 1000) ENABLE,
  PRIMARY KEY ("ID") ENABLE
);