CREATE TABLE GROUPS
(
  GROUP_NUMBER SMALLINT(4) UNIQUE NOT NULL,
  FACULTY      VARCHAR(100),
  ID_GROUP           INT          AUTO_INCREMENT,
  CHECK (GROUP_NUMBER > 1000),
  PRIMARY KEY (ID_GROUP)
);