CREATE TABLE "STUDENTS"
(
  "NAME"         VARCHAR2(200) NOT NULL ENABLE,
  "GROUP_NUMBER" NUMBER(10, 0) NOT NULL ENABLE,
  "DATE"         DATE,
  "ID"           NUMBER(10, 0),
  "CURATOR"      NUMBER(10, 0),
  CHECK (GROUP_NUMBER > 1000) ENABLE
);
ALTER TABLE "STUDENTS" ADD FOREIGN KEY ("GROUP_NUMBER")
REFERENCES "GROUPS" ("GROUP_NUMBER") ENABLE;