CREATE TABLE "STUDENTS_TEST"
(
  "NAME"     VARCHAR2(200) NOT NULL ENABLE,
  "GROUP_ID" NUMBER(10, 0),
  "DATE"     DATE,
  "ID"       NUMBER(10, 0),
  "CURATOR"  NUMBER(10, 0),
  CHECK (GROUP_NUMBER > 1000) ENABLE
);
ALTER TABLE "STUDENTS" ADD FOREIGN KEY ("GROUP_ID")
REFERENCES "GROUPS" ("GROUP_NUMBER") ENABLE;