CREATE TABLE "STUDENTS_TEST"
(
  "NAME"     VARCHAR2(200) NOT NULL ENABLE,
  "GROUP_ID" NUMBER(10, 0) NOT NULL,
  "DATE"     DATE NOT NULL ,
  "ID"       NUMBER(10, 0) UNIQUE NOT NULL,
  "CURATOR"  NUMBER(10, 0)
);
ALTER TABLE "STUDENTS_TEST" ADD FOREIGN KEY ("GROUP_ID")
REFERENCES "GROUPS_TEST" ("ID") ENABLE;