CREATE OR REPLACE TRIGGER CURATOR
BEFORE DELETE ON STUDENTS
FOR EACH ROW
  DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
    N NUMBER;
  BEGIN
    sys.dbms_job.submit(n, 'UPDATE STUDENTS SET CURATOR = NULL WHERE CURATOR =' || :OLD.ID || ';');
    COMMIT;
  END CURATOR